export type AppRole = "Founder" | "Administrator" | "Finance" | "Viewer" | "Agent" | "Customer" | "Sales";
export type SetupAccess = "full" | "read" | "denied";
export type LayoutAccess = "full" | "read" | "inventory" | "denied";
export declare function normalizeRole(raw: unknown): AppRole;
export declare function setupAccessForRole(role: unknown): SetupAccess;
export declare function layoutAccessForRole(role: unknown): LayoutAccess;
export declare function canEditSetup(role: unknown): boolean;
export declare function canViewSetup(role: unknown): boolean;
export declare function canChangeLifecycle(role: unknown): boolean;
export declare function canChangePublishFlags(role: unknown): boolean;
export declare function canPriceOverride(role: unknown): boolean;
export declare function canOpenProjectWorkspace(role: unknown): boolean;
export declare function canViewLayout(role: unknown): boolean;
export declare function canEditPlotMaster(role: unknown): boolean;
export declare function canCreatePlot(role: unknown): boolean;
export declare function canChangePlotStatus(role: unknown): boolean;
export declare function canBlockPlot(role: unknown): boolean;
export declare function canOverridePlotPrice(role: unknown): boolean;
export type SalesAccess = "full" | "read" | "limited" | "denied";
export declare function salesAccessForRole(role: unknown): SalesAccess;
export declare function canEditSalesOps(role: unknown): boolean;
export declare function canViewSales(role: unknown): boolean;
