/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as RegistrationsRouteImport } from './routes/registrations'
import { Route as ResaleRouteImport } from './routes/resale'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as BookingsIndexRouteImport } from './routes/bookings.index'
import { Route as BookingsBookingIdRouteImport } from './routes/bookings.$bookingId'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as OnboardingAgentRouteImport } from './routes/onboarding.agent'
import { Route as OnboardingBookingRouteImport } from './routes/onboarding.booking'
import { Route as OnboardingCustomerRouteImport } from './routes/onboarding.customer'
import { Route as OnboardingPlotRouteImport } from './routes/onboarding.plot'
import { Route as OnboardingProjectRouteImport } from './routes/onboarding.project'
import { Route as OnboardingReservationRouteImport } from './routes/onboarding.reservation'
import { Route as OnboardingVisitRouteImport } from './routes/onboarding.visit'
import { Route as PaymentsIndexRouteImport } from './routes/payments.index'
import { Route as PaymentsPaymentIdRouteImport } from './routes/payments.$paymentId'
import { Route as PlotsIndexRouteImport } from './routes/plots.index'
import { Route as PlotsEditorRouteImport } from './routes/plots.editor'
import { Route as PlotsLayoutRouteImport } from './routes/plots.layout'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ReceiptsPaymentIdRouteImport } from './routes/receipts.$paymentId'
import { Route as ReportsAgentsRouteImport } from './routes/reports.agents'
import { Route as ReportsCollectionsRouteImport } from './routes/reports.collections'
import { Route as ReportsInventoryRouteImport } from './routes/reports.inventory'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as SettingsAuditRouteImport } from './routes/settings.audit'
import { Route as SettingsCompanyRouteImport } from './routes/settings.company'
import { Route as SettingsUsersRouteImport } from './routes/settings.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationsRoute = RegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ResaleRoute = ResaleRouteImport.update({
  id: '/resale',
  path: '/resale',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsBookingIdRoute = BookingsBookingIdRouteImport.update({
  id: '/bookings/$bookingId',
  path: '/bookings/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAgentRoute = OnboardingAgentRouteImport.update({
  id: '/onboarding/agent',
  path: '/onboarding/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingBookingRoute = OnboardingBookingRouteImport.update({
  id: '/onboarding/booking',
  path: '/onboarding/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCustomerRoute = OnboardingCustomerRouteImport.update({
  id: '/onboarding/customer',
  path: '/onboarding/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPlotRoute = OnboardingPlotRouteImport.update({
  id: '/onboarding/plot',
  path: '/onboarding/plot',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingProjectRoute = OnboardingProjectRouteImport.update({
  id: '/onboarding/project',
  path: '/onboarding/project',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingReservationRoute = OnboardingReservationRouteImport.update({
  id: '/onboarding/reservation',
  path: '/onboarding/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingVisitRoute = OnboardingVisitRouteImport.update({
  id: '/onboarding/visit',
  path: '/onboarding/visit',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsIndexRoute = PaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsPaymentIdRoute = PaymentsPaymentIdRouteImport.update({
  id: '/payments/$paymentId',
  path: '/payments/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsIndexRoute = PlotsIndexRouteImport.update({
  id: '/plots/',
  path: '/plots/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsEditorRoute = PlotsEditorRouteImport.update({
  id: '/plots/editor',
  path: '/plots/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const PlotsLayoutRoute = PlotsLayoutRouteImport.update({
  id: '/plots/layout',
  path: '/plots/layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsPaymentIdRoute = ReceiptsPaymentIdRouteImport.update({
  id: '/receipts/$paymentId',
  path: '/receipts/$paymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsAgentsRoute = ReportsAgentsRouteImport.update({
  id: '/reports/agents',
  path: '/reports/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsCollectionsRoute = ReportsCollectionsRouteImport.update({
  id: '/reports/collections',
  path: '/reports/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsInventoryRoute = ReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAuditRoute = SettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCompanyRoute = SettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsersRoute = SettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/registrations': typeof RegistrationsRoute
  '/resale': typeof ResaleRoute
  '/reservations': typeof ReservationsRoute
  '/schedule': typeof ScheduleRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/booking': typeof OnboardingBookingRoute
  '/onboarding/customer': typeof OnboardingCustomerRoute
  '/onboarding/plot': typeof OnboardingPlotRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/reservation': typeof OnboardingReservationRoute
  '/onboarding/visit': typeof OnboardingVisitRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/plots/editor': typeof PlotsEditorRoute
  '/plots/layout': typeof PlotsLayoutRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/receipts/$paymentId': typeof ReceiptsPaymentIdRoute
  '/reports/agents': typeof ReportsAgentsRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/users': typeof SettingsUsersRoute
  '/agents/': typeof AgentsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/plots/': typeof PlotsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/registrations': typeof RegistrationsRoute
  '/resale': typeof ResaleRoute
  '/reservations': typeof ReservationsRoute
  '/schedule': typeof ScheduleRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/booking': typeof OnboardingBookingRoute
  '/onboarding/customer': typeof OnboardingCustomerRoute
  '/onboarding/plot': typeof OnboardingPlotRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/reservation': typeof OnboardingReservationRoute
  '/onboarding/visit': typeof OnboardingVisitRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/plots/editor': typeof PlotsEditorRoute
  '/plots/layout': typeof PlotsLayoutRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/receipts/$paymentId': typeof ReceiptsPaymentIdRoute
  '/reports/agents': typeof ReportsAgentsRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/users': typeof SettingsUsersRoute
  '/agents': typeof AgentsIndexRoute
  '/bookings': typeof BookingsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/payments': typeof PaymentsIndexRoute
  '/plots': typeof PlotsIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/documents': typeof DocumentsRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/registrations': typeof RegistrationsRoute
  '/resale': typeof ResaleRoute
  '/reservations': typeof ReservationsRoute
  '/schedule': typeof ScheduleRoute
  '/agents/$agentId': typeof AgentsAgentIdRoute
  '/bookings/$bookingId': typeof BookingsBookingIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/onboarding/agent': typeof OnboardingAgentRoute
  '/onboarding/booking': typeof OnboardingBookingRoute
  '/onboarding/customer': typeof OnboardingCustomerRoute
  '/onboarding/plot': typeof OnboardingPlotRoute
  '/onboarding/project': typeof OnboardingProjectRoute
  '/onboarding/reservation': typeof OnboardingReservationRoute
  '/onboarding/visit': typeof OnboardingVisitRoute
  '/payments/$paymentId': typeof PaymentsPaymentIdRoute
  '/plots/editor': typeof PlotsEditorRoute
  '/plots/layout': typeof PlotsLayoutRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/receipts/$paymentId': typeof ReceiptsPaymentIdRoute
  '/reports/agents': typeof ReportsAgentsRoute
  '/reports/collections': typeof ReportsCollectionsRoute
  '/reports/inventory': typeof ReportsInventoryRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/settings/audit': typeof SettingsAuditRoute
  '/settings/company': typeof SettingsCompanyRoute
  '/settings/users': typeof SettingsUsersRoute
  '/agents/': typeof AgentsIndexRoute
  '/bookings/': typeof BookingsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/payments/': typeof PaymentsIndexRoute
  '/plots/': typeof PlotsIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/documents'
    | '/login'
    | '/notifications'
    | '/registrations'
    | '/resale'
    | '/reservations'
    | '/schedule'
    | '/agents/$agentId'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/onboarding/agent'
    | '/onboarding/booking'
    | '/onboarding/customer'
    | '/onboarding/plot'
    | '/onboarding/project'
    | '/onboarding/reservation'
    | '/onboarding/visit'
    | '/payments/$paymentId'
    | '/plots/editor'
    | '/plots/layout'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/reports/agents'
    | '/reports/collections'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/audit'
    | '/settings/company'
    | '/settings/users'
    | '/agents/'
    | '/bookings/'
    | '/customers/'
    | '/payments/'
    | '/plots/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/documents'
    | '/login'
    | '/notifications'
    | '/registrations'
    | '/resale'
    | '/reservations'
    | '/schedule'
    | '/agents/$agentId'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/onboarding/agent'
    | '/onboarding/booking'
    | '/onboarding/customer'
    | '/onboarding/plot'
    | '/onboarding/project'
    | '/onboarding/reservation'
    | '/onboarding/visit'
    | '/payments/$paymentId'
    | '/plots/editor'
    | '/plots/layout'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/reports/agents'
    | '/reports/collections'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/audit'
    | '/settings/company'
    | '/settings/users'
    | '/agents'
    | '/bookings'
    | '/customers'
    | '/payments'
    | '/plots'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/documents'
    | '/login'
    | '/notifications'
    | '/registrations'
    | '/resale'
    | '/reservations'
    | '/schedule'
    | '/agents/$agentId'
    | '/bookings/$bookingId'
    | '/customers/$customerId'
    | '/onboarding/agent'
    | '/onboarding/booking'
    | '/onboarding/customer'
    | '/onboarding/plot'
    | '/onboarding/project'
    | '/onboarding/reservation'
    | '/onboarding/visit'
    | '/payments/$paymentId'
    | '/plots/editor'
    | '/plots/layout'
    | '/projects/$projectId'
    | '/receipts/$paymentId'
    | '/reports/agents'
    | '/reports/collections'
    | '/reports/inventory'
    | '/reports/sales'
    | '/settings/audit'
    | '/settings/company'
    | '/settings/users'
    | '/agents/'
    | '/bookings/'
    | '/customers/'
    | '/payments/'
    | '/plots/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  DocumentsRoute: typeof DocumentsRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  RegistrationsRoute: typeof RegistrationsRoute
  ResaleRoute: typeof ResaleRoute
  ReservationsRoute: typeof ReservationsRoute
  ScheduleRoute: typeof ScheduleRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRoute
  BookingsBookingIdRoute: typeof BookingsBookingIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  OnboardingAgentRoute: typeof OnboardingAgentRoute
  OnboardingBookingRoute: typeof OnboardingBookingRoute
  OnboardingCustomerRoute: typeof OnboardingCustomerRoute
  OnboardingPlotRoute: typeof OnboardingPlotRoute
  OnboardingProjectRoute: typeof OnboardingProjectRoute
  OnboardingReservationRoute: typeof OnboardingReservationRoute
  OnboardingVisitRoute: typeof OnboardingVisitRoute
  PaymentsPaymentIdRoute: typeof PaymentsPaymentIdRoute
  PlotsEditorRoute: typeof PlotsEditorRoute
  PlotsLayoutRoute: typeof PlotsLayoutRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ReceiptsPaymentIdRoute: typeof ReceiptsPaymentIdRoute
  ReportsAgentsRoute: typeof ReportsAgentsRoute
  ReportsCollectionsRoute: typeof ReportsCollectionsRoute
  ReportsInventoryRoute: typeof ReportsInventoryRoute
  ReportsSalesRoute: typeof ReportsSalesRoute
  SettingsAuditRoute: typeof SettingsAuditRoute
  SettingsCompanyRoute: typeof SettingsCompanyRoute
  SettingsUsersRoute: typeof SettingsUsersRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  PaymentsIndexRoute: typeof PaymentsIndexRoute
  PlotsIndexRoute: typeof PlotsIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrations': {
      id: '/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof RegistrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resale': {
      id: '/resale'
      path: '/resale'
      fullPath: '/resale'
      preLoaderRoute: typeof ResaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$bookingId': {
      id: '/bookings/$bookingId'
      path: '/bookings/$bookingId'
      fullPath: '/bookings/$bookingId'
      preLoaderRoute: typeof BookingsBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/agent': {
      id: '/onboarding/agent'
      path: '/onboarding/agent'
      fullPath: '/onboarding/agent'
      preLoaderRoute: typeof OnboardingAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/booking': {
      id: '/onboarding/booking'
      path: '/onboarding/booking'
      fullPath: '/onboarding/booking'
      preLoaderRoute: typeof OnboardingBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/customer': {
      id: '/onboarding/customer'
      path: '/onboarding/customer'
      fullPath: '/onboarding/customer'
      preLoaderRoute: typeof OnboardingCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/plot': {
      id: '/onboarding/plot'
      path: '/onboarding/plot'
      fullPath: '/onboarding/plot'
      preLoaderRoute: typeof OnboardingPlotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/project': {
      id: '/onboarding/project'
      path: '/onboarding/project'
      fullPath: '/onboarding/project'
      preLoaderRoute: typeof OnboardingProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/reservation': {
      id: '/onboarding/reservation'
      path: '/onboarding/reservation'
      fullPath: '/onboarding/reservation'
      preLoaderRoute: typeof OnboardingReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/visit': {
      id: '/onboarding/visit'
      path: '/onboarding/visit'
      fullPath: '/onboarding/visit'
      preLoaderRoute: typeof OnboardingVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/': {
      id: '/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof PaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments/$paymentId': {
      id: '/payments/$paymentId'
      path: '/payments/$paymentId'
      fullPath: '/payments/$paymentId'
      preLoaderRoute: typeof PaymentsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/': {
      id: '/plots/'
      path: '/plots'
      fullPath: '/plots/'
      preLoaderRoute: typeof PlotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/editor': {
      id: '/plots/editor'
      path: '/plots/editor'
      fullPath: '/plots/editor'
      preLoaderRoute: typeof PlotsEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plots/layout': {
      id: '/plots/layout'
      path: '/plots/layout'
      fullPath: '/plots/layout'
      preLoaderRoute: typeof PlotsLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts/$paymentId': {
      id: '/receipts/$paymentId'
      path: '/receipts/$paymentId'
      fullPath: '/receipts/$paymentId'
      preLoaderRoute: typeof ReceiptsPaymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/agents': {
      id: '/reports/agents'
      path: '/reports/agents'
      fullPath: '/reports/agents'
      preLoaderRoute: typeof ReportsAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/collections': {
      id: '/reports/collections'
      path: '/reports/collections'
      fullPath: '/reports/collections'
      preLoaderRoute: typeof ReportsCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/inventory': {
      id: '/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof ReportsInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/audit': {
      id: '/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof SettingsAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/company': {
      id: '/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof SettingsCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/users': {
      id: '/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof SettingsUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  DocumentsRoute: DocumentsRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  RegistrationsRoute: RegistrationsRoute,
  ResaleRoute: ResaleRoute,
  ReservationsRoute: ReservationsRoute,
  ScheduleRoute: ScheduleRoute,
  AgentsAgentIdRoute: AgentsAgentIdRoute,
  BookingsBookingIdRoute: BookingsBookingIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  OnboardingAgentRoute: OnboardingAgentRoute,
  OnboardingBookingRoute: OnboardingBookingRoute,
  OnboardingCustomerRoute: OnboardingCustomerRoute,
  OnboardingPlotRoute: OnboardingPlotRoute,
  OnboardingProjectRoute: OnboardingProjectRoute,
  OnboardingReservationRoute: OnboardingReservationRoute,
  OnboardingVisitRoute: OnboardingVisitRoute,
  PaymentsPaymentIdRoute: PaymentsPaymentIdRoute,
  PlotsEditorRoute: PlotsEditorRoute,
  PlotsLayoutRoute: PlotsLayoutRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ReceiptsPaymentIdRoute: ReceiptsPaymentIdRoute,
  ReportsAgentsRoute: ReportsAgentsRoute,
  ReportsCollectionsRoute: ReportsCollectionsRoute,
  ReportsInventoryRoute: ReportsInventoryRoute,
  ReportsSalesRoute: ReportsSalesRoute,
  SettingsAuditRoute: SettingsAuditRoute,
  SettingsCompanyRoute: SettingsCompanyRoute,
  SettingsUsersRoute: SettingsUsersRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  PaymentsIndexRoute: PaymentsIndexRoute,
  PlotsIndexRoute: PlotsIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
