#!/usr/bin/env bash
# Shared helpers for Cloud Agent setup: local Postgres + per-app .env files.
# Safe to source multiple times; every action is idempotent.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

PG_SUPERUSER="postgres"
DB_USER="bhairava"
DB_PASSWORD="bhairava"
DB_NAME="bhairava"
DB_HOST="127.0.0.1"
DB_PORT="5432"
DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}"

log() { printf '\033[1;34m[env]\033[0m %s\n' "$*"; }

ensure_postgres_installed() {
  if command -v psql >/dev/null 2>&1 && ls /usr/lib/postgresql/*/bin/postgres >/dev/null 2>&1; then
    return 0
  fi
  log "Installing PostgreSQL..."
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-contrib
}

start_postgres() {
  local ver cluster
  ver="$(ls /usr/lib/postgresql/ | sort -n | tail -1)"
  cluster="main"
  if pg_lsclusters -h 2>/dev/null | awk '{print $4}' | grep -q online; then
    log "PostgreSQL already running."
  else
    log "Starting PostgreSQL cluster ${ver}/${cluster}..."
    sudo pg_ctlcluster "${ver}" "${cluster}" start || sudo pg_ctlcluster "${ver}" "${cluster}" restart
  fi
  # Wait for readiness.
  for _ in $(seq 1 30); do
    if sudo -u "${PG_SUPERUSER}" pg_isready -q -h "${DB_HOST}" -p "${DB_PORT}" 2>/dev/null; then
      return 0
    fi
    sleep 1
  done
  log "WARNING: Postgres did not report ready in time."
}

ensure_role_and_db() {
  sudo -u "${PG_SUPERUSER}" psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='${DB_USER}') THEN
    CREATE ROLE ${DB_USER} LOGIN PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
SQL
  if ! sudo -u "${PG_SUPERUSER}" psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
    sudo -u "${PG_SUPERUSER}" createdb -O "${DB_USER}" "${DB_NAME}"
  fi
  sudo -u "${PG_SUPERUSER}" psql -q -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
  sudo -u "${PG_SUPERUSER}" psql -q -d "${DB_NAME}" -c "GRANT ALL ON SCHEMA public TO ${DB_USER};"
}

# write_env <app-dir> <port>
write_env() {
  local app_dir="$1" port="$2"
  local env_file="${REPO_ROOT}/${app_dir}/.env"
  if [ -f "${env_file}" ]; then
    log "${app_dir}/.env already exists — leaving secrets untouched."
    return 0
  fi
  local access refresh
  access="$(openssl rand -hex 32)"
  refresh="$(openssl rand -hex 32)"
  log "Writing ${app_dir}/.env"
  cat > "${env_file}" <<ENV
# Local development environment — generated by scripts/cloud-env.sh
NODE_ENV=development
DATABASE_URL=${DATABASE_URL}
DIRECT_URL=${DATABASE_URL}
JWT_ACCESS_SECRET=${access}
JWT_REFRESH_SECRET=${refresh}
ACCESS_TOKEN_TTL_SECONDS=900
REFRESH_TOKEN_TTL_DAYS=30
APP_URL=http://localhost:${port}
ENV
}

write_all_envs() {
  write_env "archive/bhairava-app" 3000
  write_env "archive/bhairava-agent" 3001
  write_env "archive/bhairava-customer" 3002
}
